# db/postgres/docker-compose.yml



services:
  postgres:
    container_name: postgres_db
    image: postgres:15
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:





