name: CI for Friendalyze Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: |
          cd backend
          mvn clean test

      - name: Build project
        run: |
          cd backend/user-service
          mvn clean package
          ls -l target/

      - name: Debug Backend Directory
        run: ls -lR backend/

      - name: Debug Build Directory
        run: ls -lR backend/user-service/

      - name: Ensure target directory exists
        run: mkdir -p backend/user-service/target/

      - name: Check if Maven build was successful
        run: ls -l backend/user-service/         

      - name: Check JAR file existence
        run: ls -l backend/user-service/target/


  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: ✅ Check if JAR file exists (before Docker build)
        run: ls -l backend/user-service/target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t farshad021/friendalyze:latest -f backend/Dockerfile backend/
          docker tag farshad021/friendalyze:latest farshad021/friendalyze:${{ github.sha }}
          docker push farshad021/friendalyze:latest
          docker push farshad021/friendalyze:${{ github.sha }}

