name: CI for Friendalyze Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build and run tests
        run: |
          cd backend
          mvn clean test

      - name: Build project
        run: |
          cd backend/user-service
          mvn clean package
          ls -l target/

      - name: Check if JAR file exists
        run: ls -l backend/user-service/target/

      - name: Package JAR file
        run: tar -cvf friendalyze.tar backend/user-service/target/friendalyze-1.0.0.jar

      - name: Extract JAR file in Docker build step
        run: tar -xvf friendalyze.tar -C backend/user-service/target/

    

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: ✅ Check if JAR file exists before Docker build
        run: ls -l backend/user-service/target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t farshad021/friendalyze:latest -f backend/Dockerfile backend/
          docker tag farshad021/friendalyze:latest farshad021/friendalyze:${{ github.sha }}
          docker push farshad021/friendalyze:latest
          docker push farshad021/friendalyze:${{ github.sha }}
