name: Test Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up JDK 19
        uses: actions/setup-java@v3 
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Build and run tests
        run: |
          cd backend
          mvn clean test
      - name: Build project

      - name: Build project
        run: |
          cd backend/user-service
          mvn clean package
          ls -l target/